include <../leg/thigh/defines.scad>

TORSO_PELVIS_PITCH_OFFSET = [0, 0, -40];
TORSO_PELVIS_PITCH_ROTATION = [90, 0, 0];
TORSO_PELVIS_PITCH_HOLDER_RADIUS = 35;
TORSO_PELVIS_PITCH_SECOND_HOLDER_RADIUS = 25;
TORSO_PELVIS_PITCH_FIRST_HOLDER_LENGTH = 45;
TORSO_PELVIS_PITCH_THIRD_HOLDER_OFFSET = 70;
TORSO_PELVIS_PITCH_THIRD_HOLDER_LENGTH = 25;
TORSO_PELVIS_PITCH_FOURTH_HOLDER_OFFSET = TORSO_PELVIS_PITCH_THIRD_HOLDER_OFFSET + TORSO_PELVIS_PITCH_THIRD_HOLDER_LENGTH;
TORSO_PELVIS_PITCH_FOURTH_HOLDER_LENGTH = 62;
TORSO_PELVIS_PITCH_AXIS_HOLE_OFFSET = 17;
TORSO_PELVIS_PITCH_AXIS_HOLE_RADIUS = 15;
TORSO_PELVIS_PITCH_AXIS_HOLE_LENGTH = TORSO_PELVIS_PITCH_FOURTH_HOLDER_OFFSET + TORSO_PELVIS_PITCH_FOURTH_HOLDER_LENGTH + 50;
TORSO_PELVIS_PITCH_POT_OFFSET = [0, -20, 0];
TORSO_PELVIS_PITCH_POT_ROTATION = [90, 90, 0];
TORSO_PELVIS_PITCH_MOTOR_OFFSET = [0, -110, 14];
TORSO_PELVIS_PITCH_MOTOR_ROTATION = [90, 90, 180];
TORSO_PELVIS_ROLL_MOTOR_OFFSET = [70, -134, 14];
TORSO_PELVIS_ROLL_MOTOR_ROTATION = [90, 90, -90];
TORSO_PELVIS_ROLL_OFFSET = TORSO_PELVIS_PITCH_OFFSET + [0, -134, 0];
TORSO_PELVIS_ROLL_AXIS_HOLE_RADIUS = 15;
TORSO_PELVIS_ROLL_AXIS_HOLE_LENGTH = 200;
TORSO_PELVIS_ROLL_ROTATION = [90, 0, 90];

TORSO_PELVIS_CENTER_CABLE_HOLE_CUBE = [POTENTIOMETER_BODY_CUBE[1] * POTENTIOMETER_PRINT_SCALE[0], 25, 200];
TORSO_PELVIS_CENTER_SCREW_ANGLE = [90, 45, 0];
TORSO_PELVIS_CENTER_SCREW_RADIUS = 4.5 / 2;
TORSO_PELVIS_CENTER_HEAD_SCREW_RADIUS = 12 / 2;
TORSO_PELVIS_CENTER_SCREW_LENGTH = 300;
TORSO_PELVIS_CENTER_SCREW_OFFSET = [0, 25, -1];
TORSO_PELVIS_CENTER_HEAD_SCREW_OFFSET = [0, 25, 7];
TORSO_PELVIS_CENTER_NUT_OFFSET = TORSO_PELVIS_CENTER_HEAD_SCREW_OFFSET;
TORSO_PELVIS_CENTER_NUT_LENGTH = 50;
TORSO_PELVIS_CENTER_BASE_CUBE = [2 * TORSO_PELVIS_PITCH_HOLDER_RADIUS, TORSO_PELVIS_PITCH_THIRD_HOLDER_OFFSET + TORSO_PELVIS_PITCH_THIRD_HOLDER_LENGTH, 10];
TORSO_PELVIS_CENTER_PITCH_MOTOR_HOLE_RADIUS = 3.2 / 2;
TORSO_PELVIS_CENTER_PITCH_MOTOR_HOLE_HEIGHT = 15;
TORSO_PELVIS_CENTER_PITCH_MOTOR_NUT_OFFSET = [0, 0, 8];
TORSO_PELVIS_CENTER_PITCH_MOTOR_NUT_ROTATION = [0, 0, -90];
TORSO_PELVIS_CENTER_PITCH_MOTOR_NUT_SHIFT = 30;
TORSO_PELVIS_CENTER_ABDOMEN_SCREW_HOLE_RADIUS = 4.5 / 2;
TORSO_PELVIS_CENTER_ABDOMEN_SCREW_HOLE_HEIGHT = 25;
TORSO_PELVIS_CENTER_ABDOMEN_SCREW_X_OFFSET = [-29, 0, 0];
TORSO_PELVIS_CENTER_ABDOMEN_SCREW_Y_OFFSET = [-30, -80];
TORSO_PELVIS_CENTER_ABDOMEN_NUT_OFFSET = [0, 0, -10];
TORSO_PELVIS_CENTER_ABDOMEN_NUT_ROTATION = [0, 0, 180];

TORSO_PELVIS_ROLL_AXIS_HOLDER_P1_BOTTOM_BASE_CUBE = [70, 88, 10];
TORSO_PELVIS_ROLL_AXIS_HOLDER_P1_AXIS_SCREW_OFFSET = TORSO_PELVIS_PITCH_OFFSET + [0, (-TORSO_PELVIS_PITCH_FIRST_HOLDER_LENGTH - TORSO_PELVIS_PITCH_THIRD_HOLDER_OFFSET) / 2, 0];
TORSO_PELVIS_ROLL_AXIS_HOLDER_P1_AXIS_SCREW_HOLE_RADIUS = 4.5 / 2;
TORSO_PELVIS_ROLL_AXIS_HOLDER_P1_AXIS_SCREW_HOLE_HEIGHT = 100;
TORSO_PELVIS_ROLL_AXIS_HOLDER_P1_AXIS_HEAD_SCREW_HOLE_RADIUS = 12 / 2;
TORSO_PELVIS_ROLL_AXIS_HOLDER_P1_AXIS_HEAD_SCREW_HOLE_OFFSET = 25;
TORSO_PELVIS_ROLL_AXIS_HOLDER_P1_AXIS_SCREW_NUT_OFFSET = 3.5;

TORSO_PELVIS_PITCH_AXIS_RADIUS = TORSO_PELVIS_PITCH_AXIS_HOLE_RADIUS - 0.5;
TORSO_PELVIS_PITCH_AXIS_LENGTH = 100;
TORSO_PELVIS_PITCH_AXIS_OFFSET = 18;

TORSO_PELVIS_ROLL_AXIS_RADIUS = TORSO_PELVIS_ROLL_AXIS_HOLE_RADIUS - 0.5;
TORSO_PELVIS_ROLL_AXIS_LENGTH = 120;
TORSO_PELVIS_ROLL_AXIS_OFFSET = -TORSO_PELVIS_ROLL_AXIS_LENGTH / 2 + 5;


TORSO_PELVIS_ROLL_AXIS_HOLDER_P2_GEAR_TEETH_NUMBER = 18;
TORSO_PELVIS_ROLL_AXIS_HOLDER_P2_GEAR_THICKNESS = 20;
TORSO_PELVIS_ROLL_AXIS_HOLDER_P2_BODY_CUBE = [-2 * TORSO_PELVIS_PITCH_OFFSET[2], 46, -2 * TORSO_PELVIS_PITCH_OFFSET[2]];

TORSO_PELVIS_PITCH_MOTOR_GEAR_TEETH_NUMBER = 10;

TORSO_PELVIS_ROLL_AXIS_HOLDER_SCREW_ROTATION = [90, 0, 180];
TORSO_PELVIS_ROLL_AXIS_HOLDER_SCREW_RADIUS = 4.5 / 2;
TORSO_PELVIS_ROLL_AXIS_HOLDER_SCREW_LENGTH = 100;
TORSO_PELVIS_ROLL_AXIS_HOLDER_HEAD_SCREW_RADIUS = 12 / 2;
TORSO_PELVIS_ROLL_AXIS_HOLDER_HEAD_SCREW_OFFSET = 25;
TORSO_PELVIS_ROLL_AXIS_HOLDER_P1_P2_SCREW_OFFSET = 20;
TORSO_PELVIS_ROLL_AXIS_HOLDER_P1_P2_NUT_ROTATION = [0, 0, 180];
TORSO_PELVIS_ROLL_AXIS_HOLDER_P1_P2_NUT_OFFSET = 25;
TORSO_PELVIS_ROLL_AXIS_HOLDER_P1_P2_NUT_SHIFT = 50;


//


module torso_pelvis_top_base(invert = false) {
  thigh_high_top_base(invert) {
    children();
  }
}
